# Number of days of inactivity before an issue becomes stale
daysUntilStale: 260
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Questo problema è stato automaticamente contrassegnato come non aggiornato 
  perché non ha avuto attività recentemente. Sarà chiuso se non si verificano ulteriori attività. 
  Considerate inoltre l'aggiornamento alle ultime versioni del tema. Grazie.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
