name: Riporta un problema
description: Segnalaci un bug o un problema che potresti aver identificato.
title: "Fornire un riepilogo generale del problema"
labels: [bug]
assignees: "-"
body:
  - type: checkboxes
    attributes:
      label: Prerequisiti
      description: Prenditi un paio di minuti per aiutare i nostri manutentori a lavorare più velocemente.
      options:
        - label: Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
          required: true
        - label: Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Descrivi il problema
      description: Fornisci un riepilogo del problema e di ciò che ti aspettavi che accadesse, inclusi i passaggi specifici da riprodurre.
    validations:
      required: true
  - type: textarea
    id: reduced-test-case
    attributes:
      label: Includi link o screenshot
      description: Includi link o screenshot del problema.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Su quale sisitema operativo stai riscontrando il problema?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Su quale browser stai riscontrando il problema?
      multiple: true
      options:
        - Qualsiasi
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Che versione del tema stai utilizzando?
      placeholder: "ad esempio 1.0.0"
    validations:
      required: true
