name: "TODO to Issue"

on: push

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6.7"
        id: "todo"
        with: 
          IGNORE: "inc/vendor/*,assets/js/*"